#file=open("data.txt","mode->r,w,a")
#file=open("data.txt","w")
#file.write("Name: Rahul\n")
#file.write("course: Python\n")
#file=open("data.txt","r")
#data=file.read()
#print(data)
#with open("data.txt","r") as file:
 #   data=file.read()
  #  print(data)
#file=open("data.txt","a")
#file.write("marks: 99\n")
#with open("data.txt","r") as file:
 #   data=file.read()
  #  print(data)
#file=open("data.txt","r")
#data=file.readline()
#data2=file.readlines()
#print(data)
#print(data2)
#file.close()
